name: Xenocraft
main: dev.hawu.plugins.xenocraft.Xenocraft
version: 1.0-SNAPSHOT
authors: [ Noah, Mio ]
description: The recreated version of the RPG Xenoblade 3.
api-version: 1.16
depend:
  - HikariLibrary
  - MultiJVMLang
commands:
  stats:
    usage: /stats
    description: Open a GUI for your own character stats.
  party:
    usage: /list
    description: Hold a party with others to fight together on fields.
  xenocraft:
    usage: /xenocraft
    aliases: [ xc ]
    description: The plugin base command.
permissions:
  xenocraft.base:
    default: op
    description: Allows access to the main plugin base command.
  xenocraft.reload:
    default: op
    description: Allows access to the command to reload messages.
