name: Xenocraft
main: dev.hawu.plugins.xenocraft.Xenocraft
version: 1.0-SNAPSHOT
authors: [ Noah, Mio ]
description: The recreated version of the RPG Xenoblade 3.
api-version: 1.16
depend:
  - HikariLibrary
  - MultiJVMLang
commands:
  stats:
    description: Open a GUI for your own character stats.
